# Generated by Django 3.2.9 on 2021-11-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalorilaskuri', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tehtava',
            old_name='otsikko',
            new_name='ruoka',
        ),
    ]
