# Generated by Django 3.2.9 on 2021-11-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalorilaskuri', '0002_rename_otsikko_tehtava_ruoka'),
    ]

    operations = [
        migrations.AddField(
            model_name='tehtava',
            name='kalori_per_100g',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
