# Generated by Django 3.2.9 on 2021-11-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalorilaskuri', '0002_rename_otsikko_tehtava_ruoka'),
    ]

    operations = [
        migrations.AddField(
            model_name='tehtava',
            name='kalori',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
